name: Deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: root
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PWD }}
          port: ${{ secrets.PORT }}
          script: |
<<<<<<< HEAD
            cd gozar-salor
            git pull git pull origin main
=======
            cd /home/ubuntu/gozar-saleor
            git pull origin main
>>>>>>> f7430fdaa (lord-a2k/fix-workflow)
